version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    env_file:
      - ./backend/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
  frontend:
    build: ./frontend
    ports:
      - "3001:3000" # Expose frontend on 3001, assuming it runs on 3000 internally
    environment:
      - REACT_APP_BACKEND_URL=http://backend:3000/api
    depends_on:
      - backend
  mongodb:
    image: mongo:4.4.6
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb
